from .unknown_model import get_unknown_model_prompt, HELPFUL_PROMPTS, MANIPULATIVE_PROMPTS
from .truthbot import get_truthbot_prompt
from .user_model import get_user_system_prompt, get_belief_elicitation_prompt, get_initial_question_prompt, get_followup_prompt
from .manipulation_guesser import get_manipulation_guesser_prompt
